http:
  middlewares:
    simpleAuth:
      basicAuth:
        users:
          - 'username:hashedPassword'
    # For Bitwarden
    bw-stripPrefix:
      stripPrefix:
        prefixes:
          - /notifications/hub
        forceSlash: false
