# Docker Compose for Bitwarden
version: '3.7'
services:
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    restart: always
    volumes:
      - ./bw-data:/data
    environment:
      - ADMIN_TOKEN=ADMINToken # Generate a Admin Token
      - WEBSOCKET_ENABLED=true
      - WEB_VAULT_ENABLED=true
      - INVITATIONS_ALLOWED=true
    networks:
      - web
    labels:
      # Entry Point for https
      - "traefik.http.routers.bitwarden-secure.rule=Host(`sub.domain.tld`)"
      - "traefik.http.routers.bitwarden-secure.service=bitwarden-service"
      - "traefik.http.routers.bitwarden-secure.tls.certresolver=lets-encrypt"
      - "traefik.http.services.bitwarden-service.loadbalancer.server.port=80"
      # websocket
      - "traefik.http.routers.bitwarden-ws.rule=Host(`sub.domain.tld`) && Path(`/notifications/hub`)"
      - "traefik.http.middlewares.bitwarden-ws=bw-stripPrefix@file"
      - "traefik.http.routers.bitwarden-ws.service=bitwarden-websocket"
      - "traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012"
networks:
  web:
    external: true